### ISSUE TITLE
`filter not found`

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden-synapse-modules#13]
```
2021-06-15 11:45:31,911 synapse.util(157) [ERROR   ]: sentinel Looping call died
Traceback (most recent call last):
  File "/synapse-venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 167, in maybeDeferred
    result = f(*args, **kw)
  File "/synapse-venv/lib/python3.9/site-packages/raiden_synapse_modules/pfs_presence_router.py", line 197, in check_filters
    for receipt in self.block_filter.get_new_entries():
  File "/synapse-venv/lib/python3.9/site-packages/web3/_utils/filters.py", line 164, in get_new_entries
    log_entries = self._filter_valid_entries(self.eth_module.get_filter_changes(self.filter_id))
  File "/synapse-venv/lib/python3.9/site-packages/web3/module.py", line 58, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/synapse-venv/lib/python3.9/site-packages/web3/manager.py", line 158, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'filter not found'}
2021-06-15 11:45:31,913 twisted(258) [CRITICAL]: sentinel Unhandled error in Deferred:
2021-06-15 11:45:31,913 twisted(258) [CRITICAL]: sentinel 
Traceback (most recent call last):
  File "/synapse-venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 167, in maybeDeferred
    result = f(*args, **kw)
  File "/synapse-venv/lib/python3.9/site-packages/raiden_synapse_modules/pfs_presence_router.py", line 197, in check_filters
    for receipt in self.block_filter.get_new_entries():
  File "/synapse-venv/lib/python3.9/site-packages/web3/_utils/filters.py", line 164, in get_new_entries
    log_entries = self._filter_valid_entries(self.eth_module.get_filter_changes(self.filter_id))
  File "/synapse-venv/lib/python3.9/site-packages/web3/module.py", line 58, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/synapse-venv/lib/python3.9/site-packages/web3/manager.py", line 158, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'filter not found'}
```

**Comment by weilbith** [comment]
I'm sorry, I wasn't very careful and did not see this issue. We can close this, as it gets handled in more detail by #22
