### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden-synapse-modules#9]
There is an unhandled exception when losing connection to the ethereum rpc:

```
# transport04: docker logs rsb_synapse_1 |& grep "2021-04-20 15:38:36,054" --after 300

2021-04-20 15:37:44,031 synapse.access.http.8008(372) [INFO    ]: GET-24234 104.248.90.246 - 8008 - {None} Processed request: 0.001sec/-0.000sec (0.001sec, 0.000sec) (0.000sec/0.000sec/1) 150B 200 "GET /_matrix/client/r0/profile/@0x94dee8e391410a9ebba791b187df2d993212c849:transport.transport04.raiden.network/displayname?access_token=<redacted> HTTP/1.1" "python-requests/2.24.0" [0 dbevts]
2021-04-20 15:37:44,037 synapse.http.servlet(218) [WARNING ]: POST-24235 Unable to parse JSON: Expecting value: line 1 column 1 (char 0)
2021-04-20 15:37:44,039 synapse.access.http.8008(372) [INFO    ]: POST-24235 104.248.90.246 - 8008 - {@0x94dee8e391410a9ebba791b187df2d993212c849:transport.transport04.raiden.network} Processed request: 0.003sec/-0.000sec (0.001sec, 0.000sec) (0.000sec/0.001sec/2) 120B 404 "POST /_matrix/client/r0/join/%23raiden_rinkeby_monitoring%3Atransport.transport04.raiden.network?access_token=<redacted> HTTP/1.1" "python-requests/2.24.0" [0 dbevts]
2021-04-20 15:38:36,054 synapse.util(153) [ERROR   ]: sentinel Looping call died
Traceback (most recent call last):
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/synapse-venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='parity.goerli.ethnodes.brainbot.com', port=8545): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/synapse-venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 167, in maybeDeferred
    result = f(*args, **kw)
  File "/synapse-venv/lib/python3.9/site-packages/raiden_synapse_modules/pfs_presence_router.py", line 197, in check_filters
    for receipt in self.block_filter.get_new_entries():
  File "/synapse-venv/lib/python3.9/site-packages/web3/_utils/filters.py", line 164, in get_new_entries
    log_entries = self._filter_valid_entries(self.eth_module.get_filter_changes(self.filter_id))
  File "/synapse-venv/lib/python3.9/site-packages/web3/module.py", line 58, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/synapse-venv/lib/python3.9/site-packages/web3/manager.py", line 154, in request_blocking
    response = self._make_request(method, params)
  File "/synapse-venv/lib/python3.9/site-packages/web3/manager.py", line 133, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/exception_retry_request.py", line 104, in middleware
    return make_request(method, params)
  File "/synapse-venv/lib/python3.9/site-packages/web3/providers/rpc.py", line 92, in make_request
    raw_response = make_post_request(
  File "/synapse-venv/lib/python3.9/site-packages/web3/_utils/request.py", line 39, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "/synapse-venv/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='parity.goerli.ethnodes.brainbot.com', port=8545): Read timed out. (read timeout=10)
2021-04-20 15:38:36,057 twisted(259) [CRITICAL]: sentinel Unhandled error in Deferred:
2021-04-20 15:38:36,057 twisted(259) [CRITICAL]: sentinel 
Traceback (most recent call last):
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/synapse-venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/synapse-venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='parity.goerli.ethnodes.brainbot.com', port=8545): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/synapse-venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 167, in maybeDeferred
    result = f(*args, **kw)
  File "/synapse-venv/lib/python3.9/site-packages/raiden_synapse_modules/pfs_presence_router.py", line 197, in check_filters
    for receipt in self.block_filter.get_new_entries():
  File "/synapse-venv/lib/python3.9/site-packages/web3/_utils/filters.py", line 164, in get_new_entries
    log_entries = self._filter_valid_entries(self.eth_module.get_filter_changes(self.filter_id))
  File "/synapse-venv/lib/python3.9/site-packages/web3/module.py", line 58, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/synapse-venv/lib/python3.9/site-packages/web3/manager.py", line 154, in request_blocking
    response = self._make_request(method, params)
  File "/synapse-venv/lib/python3.9/site-packages/web3/manager.py", line 133, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/synapse-venv/lib/python3.9/site-packages/web3/middleware/exception_retry_request.py", line 104, in middleware
    return make_request(method, params)
  File "/synapse-venv/lib/python3.9/site-packages/web3/providers/rpc.py", line 92, in make_request
    raw_response = make_post_request(
  File "/synapse-venv/lib/python3.9/site-packages/web3/_utils/request.py", line 39, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "/synapse-venv/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/synapse-venv/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='parity.goerli.ethnodes.brainbot.com', port=8545): Read timed out. (read timeout=10)
2021-04-20 15:38:36,059 synapse.access.http.8008(372) [INFO    ]: GET-24236 192.168.160.5 - 8008 - {None} Processed request: 0.000sec/-0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 394B 200 "GET /_matrix/client/versions HTTP/1.1" "Go-http-client/1.1" [0 dbevts]
2021-04-20 15:38:36,061 synapse.access.http.8008(372) [INFO    ]: GET-24238 192.168.160.5 - 8008 - {None} Processed request: 0.000sec/-0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 394B 200 "GET /_matrix/client/versions HTTP/1.1" "Go-http-client/1.1" [0 dbevts]
2021-04-20 15:38:36,064 synapse.access.http.8008(372) [INFO    ]: GET-24204 192.168.160.1 - 8008 - {@0x6e34409ec4727c8a86e67613e39b6935c0136bdc:transport.transport04.raiden.network} Processed request: 70.340sec/-0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 349B 200 "GET /_matrix/client/r0/sync?timeout=30000&since=s6131_121807_0_1_1_2655_453_124836_1&access_token=<redacted> HTTP/1.1" "python-requests/2.24.0" [0 dbevts]
2021-04-20 15:38:36,067 synapse.access.http.8008(372) [INFO    ]: GET-24202 192.168.160.1 - 8008 - {@0x09207b8ea6de0f7dfc5d7a697ab7b0330493e2bd:transport.transport04.raiden.network} Processed request: 70.346sec/-0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 349B 200 "GET /_matrix/client/r0/sync?timeout=60000&since=s6131_121807_0_1_1_2655_453_124836_1&filter=0&access_token=<redacted> HTTP/1.1" "python-requests/2.25.1" [0 dbevts]
```

Same on `transport03`
```
2021-04-20 15:38:49,948 synapse.util(153) [ERROR   ]: sentinel Looping call died
```

`transport01`, `transport03` and `transport05` did not see this.

**Comment by ulope** [comment]
The Question is what the correct Behaviour should be here.
Either we just ignore / log the error or stop the entire Synapse process.

I guess since adding a new service registration is a relatively rare occurrence it's ok to be without blockchain connection for a while and therefore just logging the problem would be ok.

Opinions?

**Comment by konradkonrad** [comment]
> I guess since adding a new service registration is a relatively rare occurrence it's ok to be without blockchain connection for a while and therefore just logging the problem would be ok.

I'd agree! If we're already confident that we'll move ahead with this setup we could also have a guard that tears down synapse on something like
- latest blocks timestamp older than `1h` and/or
- last successful eth rpc connection older than `1h`

That should help detecting being on a bad fork and consistently having lost the rpc connection.

What do you think?
